#!/bin/sh
#
# ndb_mgmd         Start/Stop the ndb_mgmd.
#
# chkconfig: 2345 40 60
# description: MySQL NDB Management Daemon
#
# processname: ndb_mgmd
# pidfile: 
#
# Source function library.
. /etc/rc.d/init.d/functions

CLUSTERDIR=/var/lib/mysql-cluster
NDBMGMD=/usr/sbin/ndb_mgmd
NDBMGM=/usr/bin/ndb_mgm

case "$1" in
  start)
        echo -n "Starting ndb_mgmd: "
	cd $CLUSTERDIR
        daemon $NDBMGMD
        echo
        ;;
  stop)
        echo -n "Stopping ndb_mgmd: "
        killproc ndb_mgmd
        echo 
        ;;
  clusterstop)
        echo -n "Shutting Down Cluster: "
        $NDBMGM -e shutdown
        echo
        ;;
  *)
        echo "Usage: $0 {start|stop|clusterstop}"
        exit 2
esac

exit 0
