#!/bin/sh
#
# npgarp        This shell script takes care of starting and stopping
#               nessus.
#
# chkconfig: - 89 11
# description: nessus provides host scanning for the netpass service

# startup order should be:
#   1. iptables            2345 08 92
#   2. mysql               2345 78 12
#   3. netpass-ha          2345 89 11
#   4. garp                    ''
#   5. portmover               ''
#   6. resetport               ''
#   7. apache              2345 90 10    
#   8. dhcrelay            2345 91 09  <- change from 66/34
#
# this script doesn 3-6. the rest is handled by other initscripts

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

[ -f /etc/sysconfig/netpass ] && . /etc/sysconfig/netpass

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

B=/opt/netpass


RETVAL=0
prog="netpass"

start() {
	# Start daemons.
	echo -n $"Starting garp: "
	${B}/bin/garpctl -q start
	if [ $? == 0 ]; then 
	    success "garp shutdown"
	else
	    failure "garp shutdown failed"
	fi
	echo

	return 0	
}

stop() {
	# Stop daemons.

	echo -n $"Shutting down garp: "
	${B}/bin/garpctl -q stop
	if [ $? == 0 ]; then 
	    success "garp shutdown"
	else
	    failure "garp shutdown failed"
	fi
	echo

	return 0
}

# See how we were called.
case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	RETVAL=$?
	;;
  status)
	${B}/bin/garpctl status
	RETVAL=$?
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|status}"
	exit 1
esac

exit $RETVAL
