#!/bin/sh
#
# npsnortd         Start/Stop the npsnortd.
#
# chkconfig: 2345 40 60
#
# Source function library.
. /etc/rc.d/init.d/functions

# Source the local configuration file
. /etc/sysconfig/npsnortd

case "$1" in
  start)
        echo -n "Starting npsnortd: "
        daemon /opt/snort/bin/npsnortd.pl -s $NPAPISERVER -S $NPAPISECRET -l $SNORTLOGFILE -r $SNORTRULESFILE -P $NPSNORTDPORT -p $SNORTPIDFILE -f /etc/init.d/snort
        echo
        ;;
  stop)
        echo -n "Stopping snort: "
        killproc npsnortd
        echo 
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 2
esac

exit 0
