#!/bin/sh -f

myecho() {
	echo `date` $*
}

B="install.d"

[ ! -d $B ] && {
    echo "run this script from the root of the netpass source tree"
    echo "for example:  cd /tmp/NetPass && install.d/convertdb"
    exit 255
}

MD=`which mysqldump 2>/dev/null `
M=`which mysql 2>/dev/null`

[ x"$MD" = "x" ] && {
    echo "can't find mysqldump command. update your PATH."
    exit 255;
}


[ x"$M" = "x" ] && {
    echo "can't find mysql command. update your PATH."
    exit 255;
}

echo "using mysqldump = $MD"
echo "      mysql     = $M"


# 2.00beta to 2.00beta (mysql cluster patch)

# we do the dump twice. cluster will sometimes report
#Error 1296: Got error 241 'Invalid schema object version' from ndbcluster when dumping table `users` at row: 0
# on the first attempt (when you run this on another server)

for i in users config pages nessusScans snortRules ; do 
	myecho "Backing up $i table to /tmp/$i.sql .."
	$MD -ce -u root netpass $i 2> /dev/null > /tmp/${i}.sql
	$MD -ce -u root netpass $i 2> /dev/null > /tmp/${i}.sql
done

##########################################################

myecho "Dropping indexes ..."

$M -fu root netpass > /dev/null 2>&1 < $B/drop-indexes.sql


##########################################################


myecho "Dropping tables ..."

$M -s -f -u root netpass > /dev/null 2>&1  < $B/drop-tables.sql


##########################################################


myecho "Creating tables ..."

$M -fu root netpass < $B/tables.sql


##########################################################

myecho "Re-importing config data ..."

for i in users config  pages nessusScans snortRules ; do 
	myecho "      from /tmp/$i.sql to table $i ..."
	$M -fu root netpass < /tmp/${i}.sql
done

myecho "Upgrade complete. Run this script on all netpass servers."

exit 0
